name: build

on: 
  push:
    branches:
    - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [K2P-USB]
    steps:
      - uses: actions/checkout@v3
      - uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.target }}
          append-timestamp: false
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
          cache-dependency-path: '**/go.sum'
      - name: Prepare
        run: |
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
      - name: Build
        run: |
          make ${{ matrix.target }}
          if [ "${{ matrix.target }}" = "K2P-NANO" ]; then
            image=$(ls trunk/images/*.trx)
            mv $image $(echo $image | sed 's/K2P/K2P-NANO/')
          fi
      - uses: actions/upload-artifact@v3
        with:
          name: images
          path: trunk/images/*.trx
  publish:
    needs: [build]
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Set Tag Name
        run: echo "TAG_ANME=$(date +%Y%m%d)" >> $GITHUB_ENV
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.TAG_ANME }}
          force_push_tag: true
      - uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: ${{ env.TAG_ANME }}
          artifacts: "images/*.trx"
          allowUpdates: true
